/**
 * Turns drizzle-kit's migrations/ folder into src/migrations/generated.ts so the migrations are
 * bundled into the app (the desktop renderer has no filesystem access).
 *
 *   tsx scripts/embed-migrations.ts          write the file
 *   tsx scripts/embed-migrations.ts --check  fail if the file is stale
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const migrationsDir = join(root, 'migrations');
const outFile = join(root, 'src/migrations/generated.ts');

interface Journal {
  entries: { idx: number; tag: string }[];
}

export function renderEmbeddedMigrations(): string {
  const journal = JSON.parse(
    readFileSync(join(migrationsDir, 'meta/_journal.json'), 'utf8'),
  ) as Journal;

  const migrations = journal.entries
    .toSorted((a, b) => a.idx - b.idx)
    .map(({ idx, tag }) => {
      // Normalise line endings so the hash is stable across git autocrlf settings.
      const source = readFileSync(join(migrationsDir, `${tag}.sql`), 'utf8').replaceAll(
        '\r\n',
        '\n',
      );
      const statements = source
        .split('--> statement-breakpoint')
        .map((s) => s.trim())
        // Drop chunks that hold only comments.
        .filter((s) => s.split('\n').some((line) => line.trim() && !line.trim().startsWith('--')));
      return {
        idx,
        tag,
        hash: createHash('sha256').update(source).digest('hex'),
        statements,
      };
    });

  return [
    '// GENERATED by scripts/embed-migrations.ts from migrations/. Do not edit.',
    '// Regenerate with `pnpm --filter @repo/database db:generate`.',
    "import type { Migration } from './types';",
    '',
    `export const migrations: readonly Migration[] = ${JSON.stringify(migrations, null, 2)};`,
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const rendered = renderEmbeddedMigrations();
  if (process.argv.includes('--check')) {
    if (readFileSync(outFile, 'utf8') !== rendered) {
      console.error('src/migrations/generated.ts is stale. Run `pnpm db:generate`.');
      process.exit(1);
    }
  } else {
    writeFileSync(outFile, rendered);
    console.log(`Embedded migrations → ${outFile}`);
  }
}
