import { describe, expect, it, vi } from 'vitest';
import { createTauriDatabaseClient } from '../lib/db-client';
import { ipc, type StatementInput } from '../lib/ipc';

describe('Tauri Database Client & Unit Of Work', () => {
  it('buffers transaction writes and dispatches as ONE db_execute_batch call', async () => {
    const executedBatches: StatementInput[][] = [];
    const querySpy = vi.spyOn(ipc, 'dbQuery').mockImplementation(async (sql) => {
      if (sql.includes('number_series')) {
        return [
          ['series_1', 'comp_1', '2026-27', 'JOURNAL_VOUCHER', 'JV', 'JV/', '', 0, 10, 1],
        ];
      }
      return [];
    });

    const batchSpy = vi.spyOn(ipc, 'dbExecuteBatch').mockImplementation(async (stmts) => {
      executedBatches.push([...stmts]);
      return stmts.length;
    });

    const client = createTauriDatabaseClient();

    await client.transaction(async (tx) => {
      // Simulate raw statements that would be generated by Drizzle
      await (tx as any).session?.client?.(
        'INSERT INTO test_table (id, name) VALUES (?, ?)',
        ['id_1', 'Item 1'],
        'run',
      );
      await (tx as any).session?.client?.(
        'INSERT INTO test_table (id, name) VALUES (?, ?)',
        ['id_2', 'Item 2'],
        'run',
      );
    });

    expect(batchSpy).toHaveBeenCalledTimes(1);
    expect(executedBatches[0]).toHaveLength(2);
    expect(executedBatches[0]?.[0]?.sql).toContain('INSERT INTO test_table');
    expect(executedBatches[0]?.[1]?.sql).toContain('INSERT INTO test_table');

    querySpy.mockRestore();
    batchSpy.mockRestore();
  });

  it('drops buffered statements and does not call dbExecuteBatch if error is thrown in transaction', async () => {
    const batchSpy = vi.spyOn(ipc, 'dbExecuteBatch').mockResolvedValue(0);
    const client = createTauriDatabaseClient();

    await expect(
      client.transaction(async (tx) => {
        await (tx as any).session?.client?.(
          'INSERT INTO test_table (id) VALUES (?)',
          ['id_fail'],
          'run',
        );
        throw new Error('Simulation abort');
      }),
    ).rejects.toThrow('Simulation abort');

    expect(batchSpy).not.toHaveBeenCalled();
    batchSpy.mockRestore();
  });
});
